# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentDesc', models.CharField(max_length=250)),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couponSerial', models.IntegerField(primary_key=True, serialize=False)),
                ('couponDesc', models.CharField(max_length=250)),
                ('value', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isUsed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('courseDesc', models.CharField(max_length=250)),
                ('courseThumbnail', models.ImageField(upload_to='thumbnails/')),
                ('coursePrice', models.IntegerField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremodels.Category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremodels.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('reviewDesc', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('reviewDate', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('takenCourseID', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremodels.Course')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('transactionDate', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremodels.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoID', models.AutoField(primary_key=True, serialize=False)),
                ('videoName', models.CharField(max_length=50)),
                ('videoFile', models.FileField(upload_to='videos/')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremodels.Course')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremodels.Video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremodels.Video'),
        ),
    ]
