# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='courseincategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='courseincategory',
            name='course',
        ),
        migrations.RemoveField(
            model_name='review',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='taker',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='course',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseInCategory',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='TakenCourse',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
